version: '3.8'

services:
  # Servicio principal de la aplicación
  cuponomics-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    # Si tienes variables de entorno, puedes descomentar y configurar:
    # env_file:
    #   - .env.local
    #   - .env.production

  # Servicio de desarrollo (opcional)
  cuponomics-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    profiles:
      - dev

# Redes (opcional, para conectar con otros servicios como base de datos)
networks:
  default:
    name: cuponomics-network 